apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: job-board-cert
  namespace: default
spec:
  secretName: job-board-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: placements.100xdevs.com
  dnsNames:
  - placements.100xdevs.com
