---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: job-board-secret
spec:
  encryptedData:
    .env: AgBvMJ9IXAi9s/di1Cdpt0bIeymlUkTYn5kwxRwyAO9UrrOzCSCr3S8z/9bW6YYN756ZFxTrWEo9DlgwNukN/7Sn2syvBc4kOA5GIaq1v1LXFXLbNUiL/enD9e+BLkur42oIakAqJql7M43gjKEd1pVVnx40GdOArsH39/2GSBfh+5LNGApPogGLtlL2WRUDXj9JwO70WAnJLtycVXEDuobxh6sx69TG7dnMMM44A94Rup4IfaXfuNkzxU4W8DtVXzG37Go2V2q9QwJwHUBwOgb3KK4LXVVUpaMEyb8PC7IKRY7SKDdY/t8jtHemobzoWviRtsE9L6z527U7MMm8yMP4jhS4wCjZ8XpURd89AxNO3FXaYgvZ9Axn1pX5BqpFPYGgGIbo2V5pJZ49PSr5qpvhJILwBv0FojGUi1FCzFMad0Cxpt6XbRanlzv/o8pktNPGgmXcAgcZ26glqeR/ca5O4x2P2oHj8ucIOTa100DFWd3JR3Ed1bb384OsZ7TFpeyqNv6cBHDU79+Ks0KpCY9mrkvh8fYCFbHIEv+szBEDkyfJoWfmLJFCtYMVMg3Tbq14y4BumlzftSwPKJ7oRm1tIGfOd46iT+g0FzSvQvfRLE0C6yfe3h9BomuGPgWn2MfOLL5sACD57ss6cPd7C22h8DGRw23wLkO0EaBy0ncJrcRQ4NjktKHq627/t1S9VV/feGqHlQ5/Ks6428Dv1jwKawdZoQyRQt25GGy1kwMfwNVb9EZ2SOJo+GgrIDAFqLq57MDc9s1d29W8piKScetUHxlGED8cocNdM486Cm4AptLBt2YvL36v7tifVBQhqRx0xoCz/XA+mIdFrrdudstkrfU2R3dA4lHX9e9/ESR2QRyeKgFhbjdTdtqn3W0xoaQGjRnpGExs5nf4S/eePcPh69G+DxBk/MD3znIjeGfAnut+gMWyieDyLpKKCf6/b7uQmJ+DZwXu48DVahhTVy7zR5l9ScDlM61jo/AqC4/qLqxqMKyvCLOpUa93F6Bq/OEO9jIzOhmZx0lek5fgJ6Me1fvFJ1HXNS4c/IiFHsPTz5BDe0HV6Wl1avlguc8thZeuhijZLuiglE8YPKZnmerRiJuE9Dg0F2/+7ZkKySlFMr89XS0nYeK/oF9SNO1K/LFrhqtu05HcUwFDIXEJ+wr2wfI6PwfcDJL0CnY2v72ai1XzigfFCpdkw+ONOrgq9+wrmT668s7AmABPZNrZfv+DhGF5dPRXA+eUyWv5ysCClVCxf8uaEvdBwmJI9crqaRxVHxNN0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: job-board-secret
    type: Opaque
