apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: algo-arena-secret
  namespace: default
spec:
  encryptedData:
    ".env": { { .algoValues.sealedSecret.encryptedData.".env" } }
  template:
    metadata:
      creationTimestamp: null
      name: algo-arena-secret
      namespace: default
    type: Opaque
