---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: job-board-staging-secret
spec:
  encryptedData:
    .env: { { .jobValues.sealedSecret.encryptedData.".env" } }
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: job-board-staging-secret
    type: Opaque
