apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    .env: { { .quizValues.sealedSecret.encryptedData.".env" } }
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
