apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trade-frontend
  template:
    metadata:
      labels:
        app: trade-frontend
    spec:
      containers:
      - name: trade-frontend
        image: {{tradeValues.frontend.image.repository}}:{{tradeValues.frontend.image.tag}}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: trade-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: trade-frontend