apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webinar-staging-cert
  namespace: default
spec:
  secretName: webinar-staging-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: staging.webinar.gg
  dnsNames:
    - staging.webinar.gg
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webinar-staging-server-cert
  namespace: default
spec:
  secretName: webinar-staging-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: staging.webinar-api.webinar.gg
  dnsNames:
    - staging.webinar-api.webinar.gg
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webinar-staging-ws-cert
  namespace: default
spec:
  secretName: webinar-staging-ws-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: staging.webinar-ws-api.webinar.gg
  dnsNames:
    - staging.webinar-ws-api.webinar.gg
