apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-staging-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-staging-frontend
  template:
    metadata:
      labels:
        app: webinar-staging-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webinar-staging-frontend
          image: 100xdevs/webinar-frontend-staging:e882857cf806110e8444e6191cb58b125e0f0cb9
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-staging-frontend
spec:
  ports:
    - port: 80
      targetPort: 4173
  selector:
    app: webinar-staging-frontend
