apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-frontend
  template:
    metadata:
      labels:
        app: webinar-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webinar-frontend
          image: 100xdevs/webinar-frontend:840b49d95a2488b2ad8fdc636d5f6ddac7da23fd
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-frontend
spec:
  ports:
    - port: 80
      targetPort: 4173
  selector:
    app: webinar-frontend
