apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-frontend
  template:
    metadata:
      labels:
        app: webinar-frontend
    spec:
      containers:
        - name: webinar-frontend
          image: 100xdevs/webinar-frontend:eabe1eacb1b33b4a24836bc426ec717d7d37f2e2
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-frontend
spec:
  ports:
    - port: 80
      targetPort: 4173
  selector:
    app: webinar-frontend
