apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-server
  template:
    metadata:
      labels:
        app: webinar-server
    spec:
      containers:
        - name: webinar-server
          image: 100xdevs/webinar-server:ce89bfef5a5d3b4e728cd8e5d56ac00eb725d622
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: secret
              mountPath: /app/apps/api/.env
              subPath: .env
      volumes:
        - name: secret
          secret:
            secretName: webinar-api-secrets
            items:
              - key: .env
                path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-server
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: webinar-server
