apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-staging-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-staging-server
  template:
    metadata:
      labels:
        app: webinar-staging-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webinar-staging-server
          image: 100xdevs/webinar-server-staging:e882857cf806110e8444e6191cb58b125e0f0cb9
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: secret
              mountPath: /app/apps/api/.env
              subPath: .env
      volumes:
        - name: secret
          secret:
            secretName: webinar-staging-api-secrets
            items:
              - key: .env
                path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-staging-server
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: webinar-staging-server
