apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-ws
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webinar-ws
  template:
    metadata:
      labels:
        app: webinar-ws
    spec:
      containers:
        - name: webinar-ws
          image: 100xdevs/webinar-ws:75ddba7b800e3d02c2e065bec27b86316667f639
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis.default.svc.cluster.local:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-ws
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webinar-ws
