apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-staging-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webinar-staging-ws
  template:
    metadata:
      labels:
        app: webinar-staging-ws
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webinar-staging-ws
          image: 100xdevs/webinar-ws-staging:e882857cf806110e8444e6191cb58b125e0f0cb9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis-staging.default.svc.cluster.local:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-staging-ws
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webinar-staging-ws
