apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webinar-ws
  template:
    metadata:
      labels:
        app: webinar-ws
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webinar-ws
          image: 100xdevs/webinar-ws:42dc9e2133f8e9fcff826be2492546ba5ff6a52f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis.default.svc.cluster.local:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-ws
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webinar-ws
