apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-backend
spec:
  destination:
    name: ''
    namespace: 'default'
    server: https://kubernetes.default.svc
  source:
    path: staging/trade
    repoURL: https://github.com/code100x/staging-ops.git
    targetRevision: HEAD
    directory:
      recurse: false
      jsonnet:
        extVars: []
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-frontend
spec:
  destination:
    name: ''
    namespace: 'default'
    server: https://kubernetes.default.svc
  source:
    path: staging/trade
    repoURL: https://github.com/code100x/staging-ops.git
    targetRevision: HEAD
    directory:
      recurse: false
      jsonnet:
        extVars: []
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
