apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trade-backend
  template:
    metadata:
      labels:
        app: trade-backend
    spec:
      containers:
        - name: trade-backend
          image: 100xdevs/trade-backend:4519a2da4f57ff20cb69f5a7dd66173af78b66d4
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: secret
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: secret
          secret:
            secretName: trade-backend-secrets
            items:
              - key: .env
                path: .env

---
apiVersion: v1
kind: Service
metadata:
  name: trade-backend
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: trade-backend