apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trade-frontend
  template:
    metadata:
      labels:
        app: trade-frontend
    spec:
      containers:
      - name: trade-frontend
        image: 100xdevs/trade-frontend:0a5d633c28af34b70b1a93acc8cadc1129272d2b
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: trade-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: trade-frontend