apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: trade-backend-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgByGPo6qZXKQuI8tFP8GCrfZwbz9Ps7sv9LkTFcDZtss83ODMHCuaatq3fx61nn8s4EMhGj3IRT4AgcbvROKq2gwctg4TWRJ7onqSXS4MUyxLGVRLfYAHsUc20He3lr+EZr+niJ4D8HxYic96R/KnWYeAJEUnf4mzsoDL5m+595KtTi4+p8H9MFIENZD0oZy9/seTT1IWdIxjQis+eV/TB1HIVpc0dEChZbZAQvszOXLOX3aW4kMP6LY5uurG+HE1FA3ys5b1NSJDVcE8BBOSy3kkYcVyyDyN6Vqx4Er/k3cIA1Cd1ifxbQEcfKTOTFKbkV1cMwCCE9NN1u4ysACAhoZmiuR/r5vaV141mpcbZnsyQrcpxSZVj2MzL8j5CYHhMBAAjQQwz+ukwdZyCNEOorRjln7uTQoTf6kR9/YwJa2+jF9NdOeS2OE6kxdvX85sqDhGHjwrCgZ8C/bcJ4ZmCgkcCjMwqrzILc2XGiUrJ2zVEFmbcIsfF8JwJRTgzbi/NnP7bfulKlAFpLY06h+9hd8EDomHGeShEVrXQ4RqxInGbNCHCl0Z3ytESOpg+RBo6h4IoAOrIPGcscIMW6ihZQcrghDoU288QdDu3AmHuSvZkvPj+QyztLUDe03gJUkZlEd8YPDk0lvvNjISqMQsZjsKeotouSsfByvW9MMyywCFqaPp3dBD2nD+Lz5fsDjBymwMbC417BAjMjhQ6V7WaXrEuYDktuMTa7xg26VhVRkap2GyFEPQvDZCGQL9caYOSbRqhSL44E/nGjsQHVYx5qs0Q9XI6nY2MuM0IRHdLgzJdpUl3nhVa5F+AZIiUTc00awCpI0vO2rjioNj3y8my0mz6asZlXY1u3FWGx6ObPSp7SWGtfxKntXmQlkd+71Bu6Ks0u/COv7AaWITjZfNQo2obr0+RVr6cofnnEykZmJl8X6QI44760dAnm1KFMUfL45eiAh48MaFDs83MF7P1K9zfvddKu7XtVO9qnzf8nuw9PHaU/GrCAY1h04pT85+7B6g==
  template:
    metadata:
      creationTimestamp: null
      name: trade-backend-secrets
      namespace: default
    type: Opaque
