apiVersion: apps/v1
kind: Deployment
metadata:
  name: qanda-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qanda-frontend
  template:
    metadata:
      labels:
        app: qanda-frontend
    spec:
      containers:
      - name: qanda-frontend
        image: 100xdevs/qanda-frontend:307838c46bea951a2a6db156cab07df8c3b61167
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: qanda-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: qanda-frontend