apiVersion: v1
kind: Service
metadata:
  name: photo-ai-frontend
spec:
  selector:
    app: photo-ai-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: photo-ai-backend
spec:
  selector:
    app: photo-ai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP