apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dailycode-cert
  namespace: default
spec:
  secretName: dailycode-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: projects.100xdevs.com
  dnsNames:
  - projects.100xdevs.com
