apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-backend-server
  template:
    metadata:
      labels:
        app: quiz-backend-server
    spec:
      containers:
        - name: quiz-backend-server
          image: dipenbhat557/project-platform-server:3a836b5fcf8912f2eaeea79f32a2fc3c688330a8
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_HOST
              value: "redis://redis.default.svc.cluster.local:6379"
          volumeMounts:
            - name: secret
              mountPath: /app/.env
              subPath: .env
      imagePullSecrets:
        - name: quiz-regcred
      volumes:
        - name: secret
          secret:
            secretName: backend-secrets
            items:
              - key: .env
                path: .env
               
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-server
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: quiz-backend-server
