apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quiz-cert
  namespace: default
spec:
  secretName: quiz-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: quiz.superdev.fun
  dnsNames:
  - quiz.superdev.fun
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quiz-backend-cert
  namespace: default
spec:
  secretName: quiz-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: quiz-backend.superdev.fun
  dnsNames:
  - quiz-backend.superdev.fun