apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: quiz-frontend
        image: dipenbhat557/project-platform-frontend:99d0ac49096c504946d91d6b63390ab067cdef1b
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: quiz-regcred

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: quiz-frontend