apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: quiz-frontend
        image: dipenbhat557/project-platform-frontend:28d9fece6856d225b67ceb590697c9b7c6247f0b
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: quiz-regcred

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: quiz-frontend