---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgCqOvgGAYXn+gJvaFlPbgNl4pvZ0Klko5RZat2aCbPmK5hRputGks42YZ40E3SNFMO9OtbFv9MtuotzMMgBphbprkKGGSTsb0jcandUUFWT0XPcXey6OJcHQ9iP6VRNhH8gtxouLj2GyjAYhguk+Xk+i6uIGDtT8srv4FDJhEF0i1PSFS5JUsUBj4hchVtONTa9btiYlhtjbct/+4D0aCebZ/npPyrsJF8vKC526DFlG6lhfTP8NtJX5IjPRRqOJLtdoiejvZHP+fcuQaFePKoN4J5fLi3BJvrX5Aw6hVWOa04/jJAb3Kh8oVqm8PsxoQtsH5QBvwjTOPZDp+UNT+zpQjfh32Dv9TAKluIGg67bO4/xJFJBlYffAuxY74w5zeRhNAr10KcA4I3hydGgQrYKVdpXNQrJ8OHJl1kBuFk8J8Ye6blnX/mRDkIiyFsFbtYkbMPAyNq6miVuoH7yuglauNOqdtF8dTsgUL/89qPFHVV1QMfMV/vh7s14Zw8Qg4M3FLGxHNVBJpZwDBhpAsxI9LsXkduINNC+RF9nLZfoerLyGNxAYsCx7SITYqxKJac73qCQmWuYENXXSoEF0cULE6qEbw9/5tIYZUdy/K0b6PGneXiEHeuNlhgRfCx2X1FXaVm4mKdGngE3FoRY5esM1KItRbXeAxnLEdyqHTw+iEA8HwqjeBrRuTlsvp/PJtuQkBdrPgoJaqz+SE8fB46Ma5dYtM43qZRL625uioPbDiRvMD1VCSuPN3b+Dkb9wEh8lI6Kc5IlkBRKh2Pqt84dLVyRp3x/1MZPrCxTuHWVArR8WZVDfwHQ/UITQUvTuOh4SS3KkPSD0cxhjsWu26gEfXsrRx7xtjT3gjnoKWChogro4sEmuKwcqNBn5p64SEwgEHzPeJMpquoNjerXblNRaBJrFOQwAp8YUTBmu1lHLNWEX0b8q/h4jb3D84Dc/7kbYVcbqVXJR9JdAku8JY2BX0PtEihPTm5zBSld1t5IuHG9tb6CgM7moY+mwGQZ+22xrzRPpWjOXhrfQM2k8AAZi3KmylcifBy4bQYfRawopc9yTGpzpermrh7jHBgieW+66/c2G1v2DNXUjwPvWUsXc4RUJ/cLNqTUEYuZMfwk9MYUJcolKg38oyZJQFnAZyjPnHS/qByIs3NEdpwFnkGW+3zJDFu5g6ZNp33TiLCKOvD5LQIJVrwy+YrXgFrwgydZtD+4JccUDneawpNhuKLU1aFzuAg73wulb3C7erU4NlRW/OUZ3Ss/u41ZK9k8LLmZ84vmicPliLLMRVlg+th1sOTh9GsN9A03V5o34vLuZ0OxcAYXVPnlvQf2KQPTAyLxw/AViacYw3r3rmMBS8MMkK2E+Quclxp1+zvSt/MfGV3TVhmCtxNua7xT+e420+PSdouHGF7eRr2EGPkyDVZu8go5J4+pJy20AalSvb3960vVJxSv4CRC7vaQf6bxJgQnP590ufih9WIE8SQfTFacPKB5UrGt52AE94JDh9qRO+zPFu9/2mdgdtUJwxkrsTLD5wA7pYGH0iqVF/5hOiTSauzsXeQFw6WtRQkntg2eqte9GuHtc86HkNN80YL0DPUfkJdMpSC1XT/3iw==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
