apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgAlIufDSfQV2N89rHen0qlXIlniUBCqYv6wBMPqE2D/Ui0aj1QxRstpCImpAR12Wz0S+Gq4LEprXUrQMuWUfbEYURRhclXnopLficsSe+VWojo8gW6QP7gcM1oUQFqn17Qbko4eSv8xNj9+az8ayy9F09FMe+heMLxv4xktlWKKg1dfxvjN6jITFiDutGjKabrJcZ8QtgY5658Y3JrR0VktR7r/tYxOPxKJ65MJM4XOhIeynPy61WGDUYvXVFo4ja5Ebhm7E0O5S0KL6fXZH6oK2L9kQorZPUXhDdpNxP5RlMmwiFaxF5D8W8r6sRRs8t9yvMtujX/UzKsP1FiaDVOmeEB24DGhem8qOdpU6CBrl/VcvK0/g9/M9pnSpaDXZ4Ome2zK40k3vb8jCMUwfBHak3wbOLd2jio19pGLeDTCvxKMjAr/LoZQqFojse4cQiov/kzR0uHkRsjBNNbl0SZPfxoUU9RDvxRAUxJWmc2iqwqjjUwfYSa0pdToLFGis+GoppDybqNxJvk/hqMe+ZZVj+Vkrt4uXvUz3Er7EHQXtMry7guiqUjKG07O2Grhih440Fp1mrzJQuyl43iCr6P+FuKjIJA3SjSuw1daYOCorQQ1v8ewUgBgq9nGN8pc8RVzkysdyudx36KxWFS8klIDb3J6D66Z4j/hwSWYoAwDc/1X7ryLKFVBgzTJMMzQPd0Tdh3Zl4i9FH+CiQH0kVulgbFSocCpIiG6q9qGWOrooaRt8JSIvmV3gewH3HyGono1KAh2sYkEFxNPSQG1uJWGlUaofMTSdNffr32iuJulzhKUdTQCBh7usv7TNMiWy8Vr0fD/IYFRr5T37fRSDywXFjYmai2j2P4OSWAXfJr9QPSQ85Isgd1X/YOrTVrzR9pGwawGACco8XKlyw4tdr4LKJCA2jV/PKph5330ZEDJkCwv5v6wIBCc1+G759VlQLbqPWUSVtC75/xkm7oWAj1pWAriQ4SvcqF7s9GLdAXmzdexB82M14JNYUtkQvDQgbSSHnCBYOk4XI245INwryCpYl/9gPPiRBsu3za8GW3B0FfBb5QSMHM8wB4t96JS/cFhp1pJQLjDDhA+4EvIZBcqmfXFLDujHHQPkRFcAzLaH23kNcVCx8wiDo+LeKU7gsJGk54Db6GgWGIeN46xVRQnkXtUAylKzDtGBwfQb8CcgKrdruUWUpA6phVjQ+GP0hjjCARAbxo6sm68EEm/pinCxan+sXXGj5gKJb4+120OLmjmsOuqL0TY7YuuGVFvY9jjybta+WgULKB3V1zSJ+itK+jN8vTkKrSq0d1xYRO0GtlF16xrsPPmWyWGb9Q1NzBhPJY3zKfbR/A2W1j/rQCO4T2kqM10e9q69d/NTxFJjpMf/qq1dFl6zAfzM2P3K4nB3lX33s+lJRc04XdxPfZr5Knw0LhdF2Fbk+bu2AfMoknAk+3Rmy9Ea4koVZ9DGmh9sXv/2OyH9Yo6ueG1IWoqOesFq/EZegs7ekq2kNo/IMNlxQT8DG+p7sxQCkfji1OATEpPMvFteJ/XEMKbe/ScrupXA75FTgVY2/UDazKqtlv+5hJzpEPNu0mEdPJX3xWY
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
