apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgAS7F0yiAfRV+tHynJcqakqhfCVUYI3qBxHPlv8zH74vA6mxJk3BTxMGKYcnJ11iLFu5YbcHc51/DX5inlac7bAJ16txEtQBRTSOv/qOR3cQKzm1Fn/5ytCUjULKB9NpUtIseytVPSEwHxp/yNjmeE2dJyac68Aj6QwhsjZCDbXqNATUkxE0sro+PZMQmesMjATCUzhssDy0R9eztl/wgVfwRZ1hoqxIzZBXqL/MxexpIlsqgKunsprA0wxEYu3B57ngDro1fb4myW8w3g9P5H5zBF5A+gNzQ10WY82AybI3fiC4g719FvWQTwisFZgZ5NLpOvttjheYIHpO3WIXfVTCJu2q/ZGGKZjNYpKSFUeFsO90ukugOze7hun3oeikHJN4ZkJi/rt1mxtRzECw6JM8nDyryNXOrdUvUbmALF+6qn0nvLhYZfSlke5F6CrJiiRLxFaOtO/lred2l7o3YxJMQEb+gT4aOYqFPWxq3k7blZ51lg3P/YRWtZX+N3PpsHk8SJCwh/t0Rh3PjSLYXVOib2hT/sbFDSWOoPIdgyYd2YlLryEyUWF7sfW902s9mScsGBc50E+rp5nWpUGTl3s7qqYVX1Bm281XfJoSX+QtdDWagCV/QfRhKkCzhZvbPV90PYBB/oDCR8E8GM+XrCLa/H1YQF8KHfT4fbpshKS4JjD/CVGeQi3LKRfsqpCpiuDI0xZV3VttoZlLp79WVcnvFaAAajd0MAsTjhrZ+NdKbaoxN8pb+OI/BRaFKBjW72uc3NUPv7bv98UdWhoCs7KuCDca6SVGaOEai77gPWRlNkkTafr4vOYyUPOpYkaDQbtfzQFUk3N50zpJro58BidKdNjj7YoltAPd2Tq0QxQyC9DPJyaQ5Oaoh5vuomroX/lDvIOPOBEI2+p6v9nSOR4kOXG9aeToUXev+JSWiDlIs/9cDAK0xzVXoR5DNFSMi05w0rnOOWtPYru4jDAI2Ic0eS7FaN9bDbvtxrLihR+RnKnfKaQ0HPLTnqEshvTWk7epI+j97vShGNAdgrzfy2EAyebp4pALMveS5aYecNVwiy3BWIexas98/RjreyXaI41XheyR/mjvseMgfyzgyOeQSUJbWFgs78wzyrm4CCbMlohCQfZ217TvxrexxTqgAT3XE5Op+I/r3OxMrR2+jBF0KtFgZDIMl8I1IxSNGRb+QamFbMIHxGzdPhzyYwsN2+TEaYVzzuLwohr/pqZX74lWe6mjBMXD74IgTU568wcox8YMBZT9LlLzf0S93QKqkfw0uSn7ZbRuf7i75+LJdYnGN3yvJPyuGHKWt3LOtuD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque