apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school
spec:
  destination:
    name: ''
    namespace: 'default'
    server: https://kubernetes.default.svc
  source:
    path: prod/school
    repoURL: https://github.com/code100x/staging-ops.git
    targetRevision: HEAD
    directory:
      recurse: false
      jsonnet:
        extVars: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
