apiVersion: v1
kind: PersistentVolume
metadata:
  name: school-pv-100gi
  namespace: default
spec:
  capacity:
    storage: 100Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/school"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: school-pvc-100gi
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
