apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-frontend
  template:
    metadata:
      labels:
        app: webinar-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: webinar-frontend
          image: 100xdevs/webinar-frontend:39b038b2d2d110cc0b53df36270022814fcf6399
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-frontend
spec:
  ports:
    - port: 80
      targetPort: 4173
  selector:
    app: webinar-frontend
