apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: 100xdevs/cms:45bf1849c86c94ac148813b2f61c2d08bc70a642
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secret
              mountPath: /usr/src/app/.env
              subPath: .env
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: secret
          secret:
            secretName: cms-secret
            items:
              - key: .env
                path: .env
