---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cms-secret
spec:
  encryptedData:
    .env: AgBvWB+PHPw8d+9jBTqLSMstZWLTJYBNJSEhZObZrI8Nudm+skS8lFUDHDI3sQBNFkonjvmrlr4J6VPlHp/7X0wOxBdEMXbg6Fo4euI9JCZg+NlZbaLbN5U95Gto31QARvCmwaDDb4DnikoF+xmntFIJ65mAUsjCSjBRPLj93tOMZC6VgDrw2mWQk5/bqfQTzx0CT26BCKZZouKWs6gfT8ulkQ/BDmoOcDs+qgfmt5fw0Ue1S94Icf60HKUNJG+ROaDDlpk5bvWqkeV+EEY+BBKaqGM0Fxa5v1xWAeeAzUNgUM+i2Cwe+Hc3ypzIjfitmhBu3GhWNhuHEBE86zEFeqyH5BZbFhGmVDWj270ozimaWv0McKVy8CdN6qq8x9Y8YoEIygiGZ7yaNmMALToGSOW312M2s+40J+tq4+OZkHAxraLhi5nW80yJF7HXThlLaSeHU3NpA4gd5ydcq0/8u3q828ztjN08UxqI0wrozGQzz7wDEs0NqoWyORtoDZ15F0MhmuYXToNynh5SFXIm1ufEgw7p+URyr3TUyj7wzLzGCWHJwISGk/QfaVO/DhRddIw0gW91yKqRzFoYkhDw6ic4uI9qrmmqE8b94fJ/+NmcRUZYdkx6Gun6+yXlZGZR45nPUryI6rLR6eMi3myn+StRIxcRG9eibYCpGJ497aNMq6lEvc+ipKwQMxPi+J51eKM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cms-secret
    type: Opaque
