apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-cert
  namespace: default
spec:
  secretName: chat-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chat.100xdevs.com
  dnsNames:
  - chat.100xdevs.com